Repository fabriciosantana/poo, pull requests merged in 2025-02, with the labels that each got.

#77 hello world
  assignments/00-hello/submissions/pedro-pignata/src/HelloWorld.java
Labels: Review effort 1/5

#82 Atividade do IMC
  assignments/01-imc/submissions/Pedro-Calil/src/CalculadoraIMC.java
Labels: Review effort 1/5

#79 "minha solução da tarefa 01 a 05"
  assignments/01-imc/submissions/Artur-Moraes/src/CalculadoraIMC.java
  assignments/02-area/submissions/Artur-moraes/src/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/Artur-Moraes/src/Fibonacci.java
  assignments/04-elephant/submissions/Artur-Moraes/src/PassosElefante.java
  assignments/05-password/submissions/Artur-Moraes/src/FortalecerSenha.java
Labels: Review effort 3/5

#89 Leitura mais exercicio 1 e 2
  assignments/01-imc/submissions/pedro-pignata/src/CalculadoraIMC.java
  assignments/02-area/submissions/pedro-pignata/src/CalculadoraPoligono.java
  readings/01-history/pedro-pignata.pdf
Labels: Review effort 2/5
