Repository fabriciosantana/poo, pull requests merged in 2025-03, with the labels that each got.

#84 Resolvidos os exercícios 1 e 2
  assignments/01-imc/submissions/guilherme-portas/src/CalculadoraIMC.java
  assignments/02-area/submissions/guilherme-portas/src/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/guilherme-portas/src/Fibonacci.java
  assignments/04-elephant/submissions/guilherme-portas/src/PassosElefante.java
  assignments/05-password/submissions/guilherme-portas/src/FortalecerSenha.java
Labels: Review effort 2/5

#94 Fortalecer Senha
  assignments/05-password/submissions/pedro-pignata/src/FortalecerSenha.java
Labels: Review effort 2/5

#95 workflow
  .github/workflows/automated-submission-assessment.yml
  .github/workflows/test-assignments-submissons.yml
Labels: Review effort 3/5

#97 PR to test worflow
  .github/workflows/test-assignments-submissons.yml
  assignments/00-hello/submissions/fabricio-santana/src/HelloWorld.java
  assignments/01-imc/submissions/fabricio-santana/src/CalculadoraIMC.java
Labels: Review effort 3/5

#81 A
  assignments/01-imc/submissions/Andreia-tiveron/src/CalculadoraIMC.java
  assignments/02-area/submissions/andreia-tiveron/src/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/andreia-tiveron/src/Fibonacci.java
  assignments/04-elephant/submissions/andreia-tiveron/src/PassosElefante.java
  assignments/05-password/submissions/andreia-tiveron/src/FortalecerSenha.java
Labels: Review effort 3/5

#83 Soluções de Atividades de 00 a 05
  assignments/00-hello/submissions/kayke-queiroz/src/HelloWorld.java
  assignments/01-imc/submissions/kayke-queiroz/src/CalculadoraIMC.java
  assignments/02-area/submissions/kayke-queiroz/src/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/kayke-queiroz/src/Fibonacci.java
  assignments/04-elephant/submissions/kayke-queiroz/src/PassosElefante.java
  assignments/05-password/submissions/kayke-queiroz/src/FortalecerSenha.java
Labels: Review effort 2/5

#104 news
  assignments/02-area/submissions/fabricio-santana/src/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/fabricio-santana/src/Fibonacci.java
  assignments/06-heart/test/HealthProfileTest.java
  assignments/06-heart/test/HeartRatesTest.java
  assignments/10-median/test/MedianCalculatorTest.java
  assignments/README.md
Labels: Review effort 2/5

#105 alterando testes
  assignments/09-collatz/test/CollatzSequenceTest.java
Labels: Review effort 1/5

#112 Ajustando testes
  assignments/06-heart/test/HeartRatesTest.java
  assignments/07-health/test/HealthProfileTest.java
  assignments/08-palindrome/test/PalindromeCheckerTest.java
  assignments/09-collatz/test/CollatzSequenceTest.java
Labels: Review effort 2/5

#107 Minha tarefa 02-área
  assignments/02-area/submissions/Pedro-Calil/src/CalculadoraPoligono.java
  readings/02-first/Pedro-Calil.pdf
Labels: Review effort 2/5

#117 novo conteúdo para as aulas.
  lectures/README.md
  lectures/examples/07-arrays/src/ArrayListCollection.java
  lectures/examples/07-arrays/src/ArrayManipulations.java
  lectures/examples/07-arrays/src/BarChart.java
  lectures/examples/07-arrays/src/CommandLineArgument.java
  lectures/examples/07-arrays/src/EmptyArray.java
  lectures/examples/07-arrays/src/EnhancedForTest.java
  lectures/examples/07-arrays/src/EvenIntegerArray.java
  lectures/examples/07-arrays/src/InitArray.java
  lectures/examples/07-arrays/src/OutOfBoundArray.java
  lectures/examples/07-arrays/src/PassArray.java
  lectures/examples/07-arrays/src/PassingArrayToMethods.java
  lectures/examples/07-arrays/src/RollDie.java
  lectures/examples/07-arrays/src/StudentPoll.java
  lectures/examples/07-arrays/src/SumArray.java
  lectures/examples/07-arrays/src/TwoDimensionalArray.java
  lectures/examples/07-arrays/src/VarargsTest.java
  lectures/examples/08-classes/src/ThisTest.java
  lectures/examples/08-classes/src/Time1.java
  lectures/examples/08-classes/src/Time1App.java
  lectures/examples/08-classes/src/Time1MemberAccessTest.java
  lectures/examples/08-classes/src/Time2.java
  lectures/examples/08-classes/src/Time2App.java
  lectures/examples/08-classes/src/bigdecimal/Interest.java
  lectures/examples/08-classes/src/composition/Date.java
  lectures/examples/08-classes/src/composition/Employee.java
  lectures/examples/08-classes/src/composition/EmployeeApp.java
  lectures/examples/08-classes/src/enum/Book.java
  lectures/examples/08-classes/src/enum/BookApp.java
  lectures/examples/08-classes/src/packageaccess/PackageDataTest.java
  lectures/examples/08-classes/src/static/Employee.java
  lectures/examples/08-classes/src/static/EmployeeApp.java
  lectures/examples/09-inheritance/payroll/pom.xml
  lectures/examples/09-inheritance/payroll/src/main/java/br/com/idp/cc/poo/Main.java
  lectures/examples/09-inheritance/payroll/src/main/java/br/com/idp/cc/poo/payroll/BasePlusCommissionEmployee.java
  lectures/examples/09-inheritance/payroll/src/main/java/br/com/idp/cc/poo/payroll/CommissionEmployee.java
  lectures/examples/09-inheritance/payroll/src/main/java/br/com/idp/cc/poo/payroll/Employee.java
  lectures/examples/09-inheritance/payroll/src/main/java/br/com/idp/cc/poo/payroll/HourlyEmployee.java
  lectures/examples/09-inheritance/payroll/src/main/java/br/com/idp/cc/poo/payroll/SalariedEmployee.java
Labels: Review effort 3/5

#115 enviando segunda tarefa
  assignments/06-heart/submissions/yuri-santana/src/HeartRates.java
  assignments/06-heart/submissions/yuri-santana/src/Main.java
  assignments/07-health/submissions/yuri-santana/src/HealthProfile.java
  assignments/07-health/submissions/yuri-santana/src/Main.java
  assignments/08-palindrome/submissions/yuri-santana/src/PalindromeChecker.java
  assignments/09-collatz/submissions/yuri-santana/src/CollatzSequence.java
  assignments/10-median/submissions/yuri-santana/src/MedianCalculator.java
  challenges/01-reverse/src/StringReverser.java
Labels: Review effort 2/5

#116 Primeiro resumo e primeira tarefa
  assignments/00-hello/submissions/rafael-lopes/src/HelloWorld.java
  readings/01-history/rafael-lopes.pdf
Labels: Review effort 1/5

#85 atividade 28/02
  assignments/01-imc/submissions/renato-portilho/src/CalculadoraIMC.java
  assignments/02-area/submissions/renato-portilho/src/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/renato-portilho/src/Fibonacci.java
  assignments/04-elephant/submissions/renato-portilho/src/PassosElefante.java
  assignments/05-password/submissions/renato-portilho/src/FortalecerSenha.java
  assignments/06-heart/submissions/renato-portilho/src/HeartRates.java
  assignments/06-heart/submissions/renato-portilho/src/Main.java
  assignments/07-health/submissions/renato-portilho/src/HealthProfile.java
  assignments/07-health/submissions/renato-portilho/src/Main.java
  assignments/08-palindrome/submissions/renato-portilho/src/PalindromeChecker.java
  assignments/09-collatz/submissions/renato-portilho/src/CollatzSequence.java
  assignments/10-median/submissions/renato-portilho/src/MedianCalculator.java
  readings/02-first/renato-portilho.pdf
Labels: Review effort 3/5

#86 TAREFAS THIAGO DELLANO
  assignments/00-hello/submissions/thiago-dellano/src/HelloWorld.java
  assignments/01-imc/submissions/Thiago-Dellano/IMCCalculator.java
  assignments/02-area/submissions/Thiago-Dellano/PoligonoCalculator.java
  assignments/03-fibonacci/submissions/Thiago-Dellano/FibonacciCalculator.java
  assignments/04-elephant/submissions/.gitkeep
  assignments/04-elephant/submissions/Thiago-Dellano/CaminhoElefante.java
  assignments/05-password/submissions/Thiago-Dellano/ReforcoSenha.java
  assignments/06-heart/submissions/Thiago-Dellano/HeartRates.java
  assignments/07-health/submissions/Thiago-Dellano/HealthProfile.java
  assignments/08-palindrome/submissions/Thiago-Dellano/PsalindromeChecker.java
  assignments/09-collatz/submissions/Thiago-Dellano/CollatzSequence.java
  assignments/10-median/submissions/Thiago-Dellano/MedianCalculator.java
  challenges/01-reverse/src/StringReverser.java
  challenges/01-reverse/src/ThiagoGabriel/StringReverser.java
  readings/01-history/thiago-dellano.pdf
  readings/02-first/Thiago-Dellano.pdf
Labels: Review effort 1/5

#88 2025.1Enviando primeira tarefa
  assignments/00-hello/submissions/Gabriela-Suares/src/HelloWorld.java
  assignments/01-imc/submissions/Gabriela-Suares/src/CalculadoraIMC.java
  assignments/02-area/submissions/Gabriela-Suares/src/Polígono Regular
  assignments/03-fibonacci/submissions/Gabriela-suares/src/Fibonacci
  assignments/04-elephant/submissions/gabriela-suares/src/Elefante
  assignments/05-password/submissions/Gabriela-Suares/src/password
  assignments/06-heart/submissions/Gabriela Suares/src/FrequenciaCardiaca.java
  assignments/07-health/submissions/Gabriela Suares/src/HealthProfile.java
  assignments/08-palindrome/submissions/PalindromeChecker.java
  assignments/10-median/submissions/MedianCalculator.java
  readings/02-first/gabriela-suares.pdf
Labels: Review effort 2/5

#90 entrega ddo hello e imc
  assignments/00-hello/submissions/gabriel-delforge/src/HelloWorld.java
  assignments/01-imc/submissions/gabriel-delforge/src/CalculadoraIMC.java
  assignments/02-area/submissions/gabriel-delforge/src/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/gabriel-delforge/src/Fibonacci.java
  assignments/04-elephant/submissions/gabriel-delforge/src/PassosElefante.java
  assignments/05-password/submissions/gabriel-delforge/src/FortalecerSenha.java
  assignments/06-heart/submissions/gabriel-delforge/src/HeartRatesCalculator.java
  assignments/07-health/submissions/gabriel-delforge/src/HealthProfileTest.java
  assignments/08-palindrome/submissions/gabriel-delforge/src/PalindromeChecker.java
  assignments/09-collatz/submissions/gabriel-delforge/src/CollatzSequence.java
  assignments/10-median/submissions/gabriel-delforge/src/MedianCalculator.java
  readings/01-history/gabriel-delforge.PDF
Labels: Review effort 1/5

#102 Entrega da 2 atividade + resumo
  assignments/06-heart/submissions/helenna-massarra/src/HeartRates.java
  assignments/07-health/submissions/helenna-massarra/src/HealthProfile.java
  assignments/08-palindrome/submissions/Helenna-Massarra/src/PalindromeChecker.java
  assignments/09-collatz/submissions/Helenna-Massarra/src/CollatzSequence.java
  assignments/10-median/submissions/Helenna-Massarra/src/MedianCalculator.java
  readings/02-first/Helenna-Massarra.pdf
Labels: Review effort 2/5

#103 realização das atividades 2
  assignments/06-heart/submissions/Samuel-Abrao/src/HeartRates.java
  assignments/07-health/submissions/Samuel-Abrao/src/HealthProfile.java
  assignments/08-palindrome/submissions/Samuel-Abrao/src/PalindromeChecker.java
  assignments/09-collatz/submissions/Samuel-Abrao/src/CollatzSequence.java
  assignments/10-median/submissions/Samuel-Abrao/src/MedianCalculator.java
  assignments/11-parking/submissions/Samuel-Abrao/src/ParkingGarage.java
  assignments/16-perfect/submissions/Samuel-Abrao/src/PerfectNumber.java
Labels: Review effort 2/5

#106 Atividades João Genaro
  assignments/00-hello/submissions/joao-genaro/src/HelloWorld.java
  assignments/01-imc/submissions/joao-genaro/src/CalculadoraIMC.java
  assignments/02-area/submissions/joao-genaro/src/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/joao-genaro/src/Fibonacci.java
  assignments/04-elephant/submissions/joao-genaro/src/PassosElefante.java
  assignments/05-password/submissions/joao-genaro/src/FortalecerSenha.java
  assignments/06-heart/submissions/joao-genaro/src/HeartRate.java
  assignments/07-health/submissions/joao-genaro/src/HealthProfile.java
  assignments/08-palindrome/submissions/joao-genaro/src/PalindromeChecker.java
  assignments/09-collatz/submissions/joao-genaro/src/CollatzSequence.java
  assignments/10-median/submissions/joao-genaro/src/MedianCalculator.java
  assignments/11-parking/submissions/joao-genaro/src/ParkingGarage.java
  assignments/16-perfect/submissions/joao-genaro/src/PerfectNumber.java
  readings/01-history/joao-genaro.pdf
  readings/01-history/rafael-lopes.pdf
  readings/02-first/joao-genaro.pdf
Labels: Review effort 1/5

#109 Exercicios 02 e Resumo 02
  assignments/06-heart/submissions/pedro-pignata/src/HeartRates.java
  assignments/06-heart/submissions/pedro-pignata/src/Main.java
  assignments/07-health/submissions/pedro-pignata/src/HealthProfile.java
  assignments/07-health/submissions/pedro-pignata/src/Main.java
  assignments/08-palindrome/submissions/pedro-pignata/src/PalindromeChecker.java
  assignments/09-collatz/submissions/pedro-pignata/src/CollatzSequence.java
  assignments/10-median/submissions/pedro-pignata/src/MedianCalculator.java
  challenges/01-reverse/src/StringReverser.java
  readings/02-first/pedro-pignata.pdf
Labels: Review effort 2/5

#110 atividades 6 a 10
  assignments/06-heart/submissions/Artur-Moraes/src/HeartRates.java
  assignments/07-health/submissions/Artur-Moraes/src/HealthProfile.java
  assignments/08-palindrome/submissions/Artur-Moraes/src/PalindromeChecker.java
  assignments/09-collatz/submissions/Artur-Moraes/src/CollatzSequence.java
  assignments/10-median/submissions/Artur-Moraes/src/MedianCalculator.java
  readings/02-first/Artur-Moraes.pdf
Labels: Review effort 2/5

#111 atividades 06 a 10 e pdf
  assignments/06-heart/submissions/kayke-queiroz/src/HeartRates.java
  assignments/07-health/submissions/kayke-queiroz/src/HealthProfile.java
  assignments/08-palindrome/submissions/kayke-queiroz/src/PalindromeChecker.java
  assignments/09-collatz/submissions/kayke-queiroz/src/CollatzSequence.java
  assignments/10-median/submissions/kayke-queiroz/src/MedianCalculator.java
  readings/02-first/kayke-queiroz.pdf
Labels: Review effort 2/5

#113 enviando resumo e atividades
  assignments/06-heart/submissions/pedro-dutra/src/HeartRates.java
  assignments/07-health/submissions/pedro-dutra/src/HealthProfile.java
  assignments/08-palindrome/submissions/pedro-dutra/src/PalindromeChecker.java
  assignments/09-collatz/submissions/pedro-dutra/src/CollatzSequence.java
  assignments/10-median/submissions/pedro-dutra/src/MedianCalculator.java
  challenges/01-reverse/src/StringReverser.java
  readings/02-first/pedro-dutra.pdf
Labels: Review effort 2/5

#119 melhorando a descrição
  challenges/02-bank/README.md
Labels: Review effort 1/5

#121 Excluindo arquivos diretorio errado
  assignments/01-imc/submissions/marcelo-mello/CalculadoraIMC.java
  assignments/02-area/submissions/marcelo-mello/CalculadoraPoligono.java
  assignments/04-elephant/submissions/marcelo-mello/PassosElefante.java
  assignments/05-password/submissions/marcelo-mello/FortalecerSenha.java
  assignments/06-heart/submissions/marcelo-mello/HeartRates.java
  assignments/07-health/submissions/marcelo-mello/HealthProfile.java
Labels: Review effort 1/5

#123 realização do challenge
  challenges/02-bank/submissions/samuel-abrao/src/Account.java
  challenges/02-bank/submissions/samuel-abrao/src/Customer.java
  challenges/02-bank/submissions/samuel-abrao/src/IDPBank.java
Labels: Review effort 3/5

#124 Enviando Primeira parte do IDPBank
  challenges/02-bank/submissions/marcelo-mello/src/IDPBank.java
Labels: Review effort 2/5

#125 Create IDPBank.java
  challenges/02-bank/submissions/kayke-queiroz/src/IDPBank.java
Labels: Review effort 2/5

#127 Começo da resolução do desafio 2
  challenges/02-bank/submissions/guilherme-portas/src/Account.java
  challenges/02-bank/submissions/guilherme-portas/src/Customer.java
  challenges/02-bank/submissions/guilherme-portas/src/Functions.java
  challenges/02-bank/submissions/guilherme-portas/src/IDPBank.java
Labels: Review effort 2/5

#128 IDPBank - allan
  challenges/02-bank/submissions/allan-samuel/src/IDPBank.java
Labels: Review effort 2/5

#129 Challenge 2
  challenges/02-bank/submissions/helenna-massarra/IDPBank.java
Labels: Review effort 2/5

#130 Challenge stringReverser
  challenges/01-reverse/src/StringReverser.java
Labels: Review effort 2/5

#143 envia terceira tarefa
  assignments/11-parking/submissions/yuri-santana/src/ParkingGarage.java
  assignments/12-savings/submissions/yuri-santana/src/SavingsAccount.java
  assignments/12-savings/submissions/yuri-santana/src/SavingsAccountApp.java
  challenges/02-bank/submissions/yuri-santana/src/Account.java
  challenges/02-bank/submissions/yuri-santana/src/Custumer.java
  challenges/02-bank/submissions/yuri-santana/src/IDPBank.java
Labels: Review effort 3/5

#141 IDPbank
  challenges/02-bank/submissions/andreia-tiveron/src/Customer.java
Labels: Review effort 2/5

#147 atividade 03
  assignments/11-parking/submissions/andreia-tiveron/src/ParkingGarage.java
  assignments/12-savings/submissions/andreia-tiveron/src/SavingsAccount.java
Labels: Review effort 2/5

#145 Atividade 11,12,13
  assignments/11-parking/submissions/kayke-queiroz/src/ParkingGarage.java
  assignments/12-savings/submissions/kayke-queiroz/src/SavingsAccountApp.java
  assignments/13-perfect/submissions/kayke-queiroz/src/PerfectNumber.java
Labels: Review effort 2/5

#148 Atividades 3
  assignments/12-savings/submissions/joao-genaro/src/SavingsAccount.java
  assignments/12-savings/submissions/joao-genaro/src/SavingsAccountApp.java
  challenges/02-bank/submissions/joao-genaro/src/Account.java
  challenges/02-bank/submissions/joao-genaro/src/Customer.java
  challenges/02-bank/submissions/joao-genaro/src/IDPBank.java
  readings/03-thinking/joao-genaro.pdf
Labels: Review effort 2/5

#146 2025.1
  assignments/11-parking/submissions/Artur-Moraes/src/ParkingGarage.java
  assignments/12-savings/submissions/Artur-Moraes/src/SavingsAccount.java
  assignments/12-savings/submissions/Artur-Moraes/src/SavingsAccountApp.java
Labels: Review effort 2/5

#140 Atividade 3
  assignments/11-parking/submissions/helenna-massarra/src/ParkingGarage.java
  assignments/12-savings/submissions/helenna-massarra/src/SavingsAccount.java
  challenges/02-bank/submissions/helenna-massarra/IDPBank.java
Labels: Review effort 2/5

#134 2025.1
  assignments/11-parking/submissions/renato-portilho/src/ParkingGarage.java
  assignments/12-savings/submissions/renato-portilho/src/SavingsAccount.java
  assignments/12-savings/submissions/renato-portilho/src/SavingsAccountApp.java
  challenges/02-bank/submissions/renato-portilho/src/Account.java
  challenges/02-bank/submissions/renato-portilho/src/Customer.java
  challenges/02-bank/submissions/renato-portilho/src/IDPBank.java
  readings/03-thinking/renato-portilho.pdf
  readings/04-concepts/renato-portilho.pdf
Labels: Review effort 3/5

#156 resoolucao tarefa 4
  assignments/13-books/submissions/Artur-Moraes/src/AudioBook.java
  assignments/13-books/submissions/Artur-Moraes/src/Book.java
  assignments/13-books/submissions/Artur-Moraes/src/BookApp.java
  assignments/13-books/submissions/Artur-Moraes/src/PrintBook.java
Labels: Review effort 2/5

#154 Atividade #4
  assignments/12-savings/submissions/marcelo-mello/src/SavingsAccount.java
  assignments/12-savings/submissions/marcelo-mello/src/SavingsAccountApp.java
  assignments/13-books/marcelo-mello/src/AudioBook.java
  assignments/13-books/marcelo-mello/src/Book.java
  assignments/13-books/marcelo-mello/src/BookApp.java
  assignments/13-books/marcelo-mello/src/PrintBook.java
Labels: Review effort 2/5

#153 IDPBank corrigido + atividade 4
  assignments/13-books/helenna-massarra/src/BookApp.java
  challenges/02-bank/submissions/helenna-massarra/src/Account.java
  challenges/02-bank/submissions/helenna-massarra/src/CheckingAccount.java
  challenges/02-bank/submissions/helenna-massarra/src/Customer.java
  challenges/02-bank/submissions/helenna-massarra/src/IDPBank.java
  challenges/02-bank/submissions/helenna-massarra/src/SalaryAccount.java
  challenges/02-bank/submissions/helenna-massarra/src/SavingsAccount.java
Labels: Review effort 2/5

#152 2025.1
  assignments/11-parking/submissions/pedro-pignata/src/ParkingGarage.java
  challenges/02-bank/submissions/pedro-pignata/src/Account.java
  challenges/02-bank/submissions/pedro-pignata/src/Customer.java
  challenges/02-bank/submissions/pedro-pignata/src/IDPBank2.java
Labels: Review effort 3/5

#142 Resolvidos exercícios da semana 3
  assignments/11-parking/submissions/guilherme-portas/src/ParkingGarage.java
  assignments/12-savings/submissions/guilherme-portas/src/SavingsAccount.java
  assignments/12-savings/submissions/guilherme-portas/src/SavingsAccountApp.java
  assignments/13-books/guilherme-portas/src/AudioBook.java
  assignments/13-books/guilherme-portas/src/Book.java
  assignments/13-books/guilherme-portas/src/BookApp.java
  assignments/13-books/guilherme-portas/src/PrintBook.java
  assignments/13-perfect/submissions/guilherme-portas/src/PerfectNumber.java
  challenges/02-bank/submissions/guilherme-portas/src/IDPBank.java
  readings/04-concepts/guilherme-portas.pdf
Labels: Review effort 2/5
