Repository fabriciosantana/poo, pull requests merged in 2025-06, with the labels that each got.

#214 Atividade-05
  challenges/04-report/submissions/marcelo-mello/RelatorioCompras.java
  challenges/04-report/submissions/marcelo-mello/compras.txt
  challenges/04-report/submissions/marcelo-mello/relatorio.txt
  challenges/05-copa/submissions/marcelo-mello/src/CopaIDPApp.java
  challenges/05-copa/submissions/marcelo-mello/src/Partida.java
  challenges/05-copa/submissions/marcelo-mello/src/Time.java
Labels: Review effort 3/5

#227 complementando readme
  lectures/examples/14-db/README.md
Labels: Review effort 1/5

#236 2025.1
  challenges/06-jdbc/submissions/pedro-pignata/src/br/edu/idp/cc/poo/dvdrental/Main.java
  challenges/06-jdbc/submissions/pedro-pignata/src/br/edu/idp/cc/poo/dvdrental/dao/FilmDAO.java
  challenges/06-jdbc/submissions/pedro-pignata/src/br/edu/idp/cc/poo/dvdrental/model/Film.java
  challenges/06-jdbc/submissions/pedro-pignata/src/br/edu/idp/cc/poo/dvdrental/util/AuditLogger.java
  challenges/06-jdbc/submissions/pedro-pignata/src/br/edu/idp/cc/poo/dvdrental/util/ConnectionFactory.java
Labels: Review effort 3/5

#233 challange 6
  assignments/15-duplicate/submissions/helenna-massarra/src/CadastroNomes.java
  challenges/06-jdbc/submissions/helenna-massarra/src/br/edu/idp/cc/poo/dvdrental/Main.java
  challenges/06-jdbc/submissions/helenna-massarra/src/br/edu/idp/cc/poo/dvdrental/dao/ActorDAO.java
  challenges/06-jdbc/submissions/helenna-massarra/src/br/edu/idp/cc/poo/dvdrental/dao/FilmDAO.java
  challenges/06-jdbc/submissions/helenna-massarra/src/br/edu/idp/cc/poo/dvdrental/model/Actor.java
  challenges/06-jdbc/submissions/helenna-massarra/src/br/edu/idp/cc/poo/dvdrental/model/Film.java
  challenges/06-jdbc/submissions/helenna-massarra/src/br/edu/idp/cc/poo/dvdrental/util/AuditLogger.java
  challenges/06-jdbc/submissions/helenna-massarra/src/br/edu/idp/cc/poo/dvdrental/util/ConnectionFactory.java
  lectures/examples/14-db/db.properties.samples
Labels: Review effort 3/5

#230 challenges 6
  challenges/06-jdbc/submissions/andreia-tiveron/src/br/edu/idp/cc/poo/dvdrental/Main.java
  challenges/06-jdbc/submissions/andreia-tiveron/src/br/edu/idp/cc/poo/dvdrental/dao/FilmDAO.java
  challenges/06-jdbc/submissions/andreia-tiveron/src/br/edu/idp/cc/poo/dvdrental/model/Film.java
  challenges/06-jdbc/submissions/andreia-tiveron/src/br/edu/idp/cc/poo/dvdrental/util/AuditLogger.java
  challenges/06-jdbc/submissions/andreia-tiveron/src/br/edu/idp/cc/poo/dvdrental/util/ConnectionFactory.java
Labels: Review effort 3/5

#228 Atividade 06 jdbc
  assignments/15-duplicate/submissions/marcelo-mello/src/EliminarNomesDuplicados.java
  challenges/06-jdbc/submissions/marcelo-mello/src/br/edu/idp/cc/poo/dvdrental/Main.java
  challenges/06-jdbc/submissions/marcelo-mello/src/br/edu/idp/cc/poo/dvdrental/dao/FilmDAO.java
  challenges/06-jdbc/submissions/marcelo-mello/src/br/edu/idp/cc/poo/dvdrental/model/Film.java
  challenges/06-jdbc/submissions/marcelo-mello/src/br/edu/idp/cc/poo/dvdrental/util/AuditLogger.java
  challenges/06-jdbc/submissions/marcelo-mello/src/br/edu/idp/cc/poo/dvdrental/util/ConnectionFactory.java
Labels: Review effort 3/5

#244 Resolvido exercicio 15
  assignments/15-duplicate/submissions/guilherme-portas/src/EliminarNomesDuplicados.java
Labels: Review effort 2/5

#243 15 - duplicate
  assignments/14-exception/submissions/samuel-abrao/Phone.java
  assignments/14-exception/submissions/samuel-abrao/PhoneApp.java
  assignments/14-exception/submissions/samuel-abrao/ValidationException.java
  assignments/15-duplicate/submissions/Samuel-Abrao/CadastroNomes.java
Labels: Review effort 2/5

#242 2025.1
  assignments/15-duplicate/submissions/pedro-pignata/src/EliminarNomesDuplicados.java
Labels: Review effort 2/5

#241 atividade coleções
  assignments/15-duplicate/submissions/andreia-tiveron/src/NomesDup.java
Labels: Review effort 2/5

#239 atividade 15
  assignments/15-duplicate/submissions/kayke-queiroz/src/Main.java
  assignments/15-duplicate/submissions/kayke-queiroz/src/NomeManager.java
  assignments/15-duplicate/submissions/kayke-queiroz/src/Util.java
Labels: Review effort 2/5

#248 Prova 2
  challenges/07-flix/submissions/samuel-abrao/src/Film.java
  challenges/07-flix/submissions/samuel-abrao/src/FilmeReader.java
  challenges/07-flix/submissions/samuel-abrao/src/ImportaFilmes.java
Labels: Review effort 3/5, Possible security concern

#249 prova pratica
  challenges/07-flix/submissions/artur-moraes/src/Film.java
  challenges/07-flix/submissions/artur-moraes/src/FilmFileReader.java
  challenges/07-flix/submissions/artur-moraes/src/IDPFlixApp.java
Labels: Review effort 3/5, Possible security concern

#250 Prova 2 - prática - allan
  challenges/07-flix/submissions/allan-samuel/src/Film.java
  challenges/07-flix/submissions/allan-samuel/src/FilmFileReader.java
  challenges/07-flix/submissions/allan-samuel/src/Main.java
Labels: Review effort 2/5, Possible security concern

#252 código da prova
  challenges/07-flix/submissions/kayke-queiroz/src/Film.java
  challenges/07-flix/submissions/kayke-queiroz/src/FilmMain.java
  challenges/07-flix/submissions/kayke-queiroz/src/FilmReader.java
Labels: Review effort 3/5, Possible security concern

#253 Segunda Prova Prática
  challenges/07-flix/submissions/pedro-dutra/src/ConexaoSupabase.java
  challenges/07-flix/submissions/pedro-dutra/src/Film.java
  challenges/07-flix/submissions/pedro-dutra/src/FilmReader.java
  challenges/07-flix/submissions/pedro-dutra/src/Main.java
Labels: Review effort 2/5, Possible security concern

#254 Prova Pratica Dois
  challenges/07-flix/submissions/pedro-pignata/src/Film.java
  challenges/07-flix/submissions/pedro-pignata/src/FilmFileReader.java
  challenges/07-flix/submissions/pedro-pignata/src/IDPFlixApp.java
  challenges/07-flix/submissions/pedro-pignata/src/Supabase.java
Labels: Review effort 3/5, Possible security concern

#255 Prova 2
  assignments/15-duplicate/submissions/joao-genaro/src/EliminadorDeDuplicates.java
  challenges/07-flix/submissions/joao-genaro/src/.DS_Store
  challenges/07-flix/submissions/joao-genaro/src/Film.java
  challenges/07-flix/submissions/joao-genaro/src/FilmeReader.java
  challenges/07-flix/submissions/joao-genaro/src/ImportaFilmes.java
  challenges/07-flix/submissions/joao-genaro/src/db.properties.sample
Labels: Review effort 3/5, Possible security concern

#256 Prova av2
  challenges/07-flix/submissions/andreia-tiveron/src/Film.java
  challenges/07-flix/submissions/andreia-tiveron/src/Flix.java
  challenges/07-flix/submissions/andreia-tiveron/src/LeitorArquivo.java
  lectures/examples/15-jpa/dvdrentalapp/src/main/resources/META-INF/persistence.xml
Labels: Review effort 4/5, Possible security concern

#260 Resolvido desafio 7 da prova prática
  challenges/07-flix/submissions/guilherme-portas/src/dvdrentalApp/Main.java
  challenges/07-flix/submissions/guilherme-portas/src/dvdrentalApp/dao/FilmDAO.java
  challenges/07-flix/submissions/guilherme-portas/src/dvdrentalApp/model/Film.java
  challenges/07-flix/submissions/guilherme-portas/src/dvdrentalApp/util/AuditLogger.java
  challenges/07-flix/submissions/guilherme-portas/src/dvdrentalApp/util/ConnectionFactory.java
  challenges/07-flix/submissions/guilherme-portas/src/dvdrentalApp/util/TextDBInserter.java
  challenges/07-flix/submissions/guilherme-portas/src/new_films.txt
Labels: Review effort 3/5
