Repository fabriciosantana/poo, pull requests merged in 2025-09, with the labels that each got.

#363 refactoring
  lectures/examples/02b-primitives-operators/src/OperatorArithmeticAddition.java
  lectures/examples/02b-primitives-operators/src/OperatorArithmeticModulus.java
  lectures/examples/02b-primitives-operators/src/OperatorAssignmentDynInit.java
  lectures/examples/02b-primitives-operators/src/OperatorAssignmentLifeTime.java
  lectures/examples/02b-primitives-operators/src/OperatorBooleanLogic.java
  lectures/examples/02b-primitives-operators/src/OperatorIncDec.java
  lectures/examples/02b-primitives-operators/src/OperatorRelational.java
  lectures/examples/02b-primitives-operators/src/OperatorRelationalEqual.java
  lectures/examples/02b-primitives-operators/src/OperatorRelationalLeapYear.java
  lectures/examples/02b-primitives-operators/src/PrimitiveTypeArea.java
  lectures/examples/02b-primitives-operators/src/PrimitiveTypeBasicMath.java
  lectures/examples/02b-primitives-operators/src/PrimitiveTypeBoolTest.java
  lectures/examples/02b-primitives-operators/src/PrimitiveTypeCasting.java
  lectures/examples/02b-primitives-operators/src/PrimitiveTypeCastingPromote.java
  lectures/examples/02b-primitives-operators/src/PrimitiveTypeCharDemo.java
  lectures/examples/02b-primitives-operators/src/PrimitiveTypeCharDemo2.java
  lectures/examples/02b-primitives-operators/src/PrimitiveTypeLight.java
  lectures/examples/02b-primitives-operators/src/PrimitveTypeVarDemo.java
  lectures/examples/02b-primitives-operators/src/VariableScope.java
  lectures/examples/02b-primitives-operators/src/VariableScopeErr.java
  lectures/examples/02c-input-output/src/BufferedReaderSample.java
  lectures/examples/02c-input-output/src/ExemploConsole.java
  lectures/examples/02c-input-output/src/ScannerSample.java
  lectures/examples/02c-input-output/src/ScannerSample2.java
  slides/01b-input-output.md
Labels: Review effort 2/5, Possible security concern

#366 Tarefa 2 POO
  assignments/06-heart/submissions/caio-amorim/src/Main.java
  assignments/07-health/submissions/caio-amorim/src/HealthProfile.java
  assignments/08-palindrome/submissions/caio-amorim/src/PalindromeChecker.java
  assignments/09-collatz/submissions/caio-amorim/src/CollatzSequence.java
  assignments/10-median/submissions/caio-amorim/src/MedianCalculator.java
Labels: Review effort 2/5

#369 6 a 10
  assignments/06-heart/submissions/artur-boudens/src/HeartRates.java
  assignments/06-heart/submissions/artur-boudens/src/HeartRatesApp.java
  assignments/07-health/submissions/artur-boudens/src/HealthProfile.java
  assignments/07-health/submissions/artur-boudens/src/HealthProfileApp.java
  assignments/08-palindrome/submissions/artur-boudens/src/PalindromeChecker.java
  assignments/09-collatz/submissions/artur-boudens/src/CollatzSequence.java
  assignments/10-median/submissions/artur-boudens/src/MedianCalculator.java
  scripts/test-assignments.sh
Labels: Review effort 3/5

#373 Assignments 6-10
  assignments/06-heart/submissions/felipe-trindade/src/HeartRates.java
  assignments/07-health/submissions/felipe-trindade/src/HealthProfile.java
  assignments/08-palindrome/submissions/felipe-trindade/src/PalindromeChecker.java
  assignments/09-collatz/submissions/felipe-trindade/src/CollatzSequence.java
  assignments/10-median/submissions/felipe-trindade/src/MedianCalculator.java
Labels: Review effort 2/5

#370 Atividades 6 - 10
  assignments/02-area/submissions/joao-antonio/src/calculadoraPoligono.java
  assignments/03-fibonacci/submissions/joao-antonio/src/fibonacci.java
  assignments/06-heart/submissions/joao-antonio/src/HeartRates.java
  assignments/07-health/submissions/joao-antonio/src/HealthProfile.java
  assignments/08-palindrome/submissions/joao-antonio/src/PalindromeChecker.java
  assignments/09-collatz/submissions/joao-antonio/src/CollatzSequence.java
  assignments/10-median/submissions/joao-antonio/src/MedianCalculator.java
  readings/03-thinking/joao-antonio3.pdf
Labels: Review effort 2/5

#378 Correção das atividades
  assignments/03-fibonacci/submissions/joao-antonio/src/Fibonacci.java
  assignments/06-heart/submissions/joao-antonio/src/HeartRates.java
  assignments/07-health/submissions/joao-antonio/src/HealthProfile.java
Labels: Review effort 2/5

#390 Atividades
  assignments/11-parking/submissions/arthur-silva.pdf/src/ParkingGarage.java
  assignments/12-savings/submissions/arthur-silva/src/SavingsAccount.java
  assignments/12-savings/submissions/arthur-silva/src/SavingsAccountApp.java
  readings/05-solid/arthur-silva.pdf
Labels: Review effort 2/5

#395 adiciona exercicios 3
  assignments/11-parking/submissions/Lucas-Pontual/src/ParkingGarage.java
  assignments/12-savings/submissions/Lucas-Pontual/src/SavingsAccount.java
  assignments/12-savings/submissions/Lucas-Pontual/src/SavingsAccountApp.java
  readings/05-solid/Lucas-Pontual.pdf
Labels: Review effort 2/5

#397 atividade 12 - SavingsAccount
  assignments/11-parking/submissions/Pablo-basilio/src/ParkingGarage.java
  assignments/12-savings/submissions/Pablo-Basilio/src/SavingsAccount.java
  assignments/12-savings/submissions/Pablo-Basilio/src/SavingsAccountApp.java
  readings/04-concepts/Pablo-basilio (2).pdf
Labels: Review effort 2/5

#401 renomeado atividade
  assignments/06-heart/submissions/lais-medeiros/src/HeartRates.java
  assignments/06-heart/submissions/lais-medeiros/src/HeartRatesApp.java
  assignments/07-health/submissions/lais-medeiros/src/HealthProfile.java
  assignments/07-health/submissions/lais-medeiros/src/HealthProfileApp.java
  assignments/08-palindrome/submissions/lais-medeiros/src/PalindromeApp.java
  assignments/08-palindrome/submissions/lais-medeiros/src/PalindromeChecker.java
  assignments/09-collatz/submissions/lais-medeiros/src/CollatzApp.java
  assignments/09-collatz/submissions/lais-medeiros/src/CollatzSequence.java
  assignments/10-median/submissions/lais-medeiros/src/MedianApp.java
  assignments/10-median/submissions/lais-medeiros/src/MedianCalculator.java
  assignments/11-parking/submissions/lais-medeiros/src/ParkingGarage.java
  assignments/12-savings/submissions/lais-medeiros/src/SavingsAccount.java
  assignments/12-savings/submissions/lais-medeiros/src/SavingsAccountApp.java
  assignments/13-books/submissions/lais-medeiros/src/AudioBook.java
  assignments/13-books/submissions/lais-medeiros/src/Book.java
  assignments/13-books/submissions/lais-medeiros/src/BookApp.java
  assignments/13-books/submissions/lais-medeiros/src/PrintBook.java
  readings/05-solid/lais-medeiros.pdf
Labels: Review effort 2/5

#409 Tarefa atividade #4 - Books
  assignments/13-books/submissions/felipe-ballarin/AudioBook.java
  assignments/13-books/submissions/felipe-ballarin/Book.java
  assignments/13-books/submissions/felipe-ballarin/BookApp.java
  assignments/13-books/submissions/felipe-ballarin/PrintBook.java
Labels: Review effort 2/5

#389 resumo 4 - Bernardo Levorsse
  assignments/06-heart/submissions/bernardo-levorsse/src/src/HeartRatesTest.java
  assignments/07-health/submissions/bernardo-levorsse/src/src/HealthProfileApp.java
  assignments/08-palindrome/submissions/bernardo-levorsse/src/src/PalindromeChecker.java
  assignments/09-collatz/submissions/bernardo-levorsse/src/src/CollatzSequence.java
  assignments/10-median/submissions/bernardo-levorsse/src/src/MedianCalculator.java
  assignments/11-parking/submissions/bernardo-levorsse/src/src/ParkingGarage.java
  assignments/12-savings/submissions/bernardo-levorsse/src/src/SavingsAccount.java
  assignments/14-exception/submissions/bernardo-levorsse/src/src/Phone.java
  assignments/14-exception/submissions/bernardo-levorsse/src/src/PhoneApp.java
  assignments/14-exception/submissions/bernardo-levorsse/src/src/ValidationException.java
  assignments/15-duplicate/submissions/bernardo-levorsse/src/src/NameRegistry.java
  readings/04-concepts/bernardo_levorsse.pdf
  readings/05-solid/bernardo_levorsse.pdf
Labels: Review effort 2/5

#414 Atividade 13
  assignments/02-area/submissions/natalia-fernandes/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/natalia-fernandes/Fibonacci.java
  assignments/04-elephant/submissions/natalia-fernandes/PassosElefante.java
  assignments/05-password/submissions/natalia-fernandes/FortalecerSenha.java
  assignments/06-heart/submissions/natalia-fernandes/HeartRates.java
  assignments/07-health/submissions/natalia-fernandes/HealthProfile.java
  assignments/08-palindrome/submissions/natalia-fernandes/PalindromeChecker.java
  assignments/09-collatz/submissions/natalia-fernandes/CollatzSequence.java
  assignments/10-median/submissions/natalia-fernandes/MedianCalculator.java
  assignments/11-parking/submissions/natalia-fernandes.src/ParkingGarage.Java
  assignments/12-savings/submissions/natalia-fernandes.src/SavingsAccount.Java
  assignments/14-exception/submissions/natalia-fernandes.src/Phone.Java
  assignments/14-exception/submissions/natalia-fernandes.src/PhoneApp.Java
  assignments/14-exception/submissions/natalia-fernandes.src/ValidationException.Java
  assignments/15-duplicate/submissions/natalia-fernandes.src/UniqueNamesApp.Java
  assignments/XX-perfect/submissions/natalia-fernandes.src/PerfectNumber.Java
Labels: Review effort 3/5

#415 Atividade 13 e 14 e atualização da 11 e 12
  assignments/11-parking/submissions/marcelo-silva/src/ParkingGarage.java
  assignments/12-savings/submissions/marcelo-silva/src/SavingsAccount.java
  assignments/12-savings/submissions/marcelo-silva/src/SavingsAccountApp.java
  assignments/13-books/submission/marcelo-silva/src/AudioBook.java
  assignments/13-books/submission/marcelo-silva/src/Book.java
  assignments/13-books/submission/marcelo-silva/src/BookApp.java
  assignments/13-books/submission/marcelo-silva/src/PrintBook.java
  assignments/14-exception/submissions/marcelo-silva/src/Phone.java
  assignments/14-exception/submissions/marcelo-silva/src/PhoneApp.java
  assignments/14-exception/submissions/marcelo-silva/src/ValidationException.java
Labels: Review effort 2/5

#416 Entrega Atividade 4
  assignments/13-books/submissions/felipe-trindade/src/AudioBook.java
  assignments/13-books/submissions/felipe-trindade/src/Book.java
  assignments/13-books/submissions/felipe-trindade/src/BookApp.java
  assignments/13-books/submissions/felipe-trindade/src/PrintBook.java
Labels: Review effort 2/5

#417 Atividade Book
  assignments/13-books/submissions/pablo-basilio/src/Book.java
  readings/05-solid/Pablo-basilio (1).pdf
Labels: Review effort 2/5

#420 Activity 13
  assignments/13-books/submissions/matheus-biolowons/src/BookApp.java
Labels: Review effort 2/5
