Repository fabriciosantana/poo, pull requests merged in 2025-04, with the labels that each got.

#166 test
  challenges/01-reverse/src/StringReverser.java
  readings/03-thinking/pedro-calil.pdf
  readings/04-concepts/pedro-calil.pdf
  readings/05-solid/pedro-calil.pdf
Labels: Review effort 1/5

#162 quarta tarefa
  assignments/13-books/submissions/yuri-santana/src/AudioBook.java
  assignments/13-books/submissions/yuri-santana/src/Book.java
  assignments/13-books/submissions/yuri-santana/src/BookApp.java
  assignments/13-books/submissions/yuri-santana/src/PrintBook.java
  challenges/02-bank/submissions/yuri-santana/src/IDPBank.java
  challenges/02-bank/submissions/yuri-santana/src/models/Account.java
  challenges/02-bank/submissions/yuri-santana/src/models/CheckingAccount.java
  challenges/02-bank/submissions/yuri-santana/src/models/Customer.java
  challenges/02-bank/submissions/yuri-santana/src/models/SalaryAccount.java
  challenges/02-bank/submissions/yuri-santana/src/models/SavingsAccount.java
Labels: Review effort 3/5

#161 2025.1
  assignments/13-books/pedro-pignata/src/BookApp.java
Labels: Review effort 2/5

#171 Adicionando resumos 3, 4 e 5
  assignments/02-area/submissions/Gabriela-Suares/src/CalculadoraPoligono.java
  assignments/03-fibonacci/submissions/Gabriela-suares/src/Fibonacci.java
  assignments/04-elephant/submissions/gabriela-suares/src/PassosElefante.java
  assignments/05-password/submissions/Gabriela-Suares/src/FortalecerSenha.java
  assignments/06-heart/submissions/Gabriela Suares/src/HeartRates.java
  assignments/08-palindrome/submissions/Gariela-suares/src/PalindromeChecker.java
  assignments/09-collatz/submissions/Gabriela-suares/src/CollatzSequence.java
  assignments/10-median/submissions/Gabirela-suares/src/MedianCalculator.java
  assignments/11-parking/submissions/Gabriela-suares/src/ParkingGarage.java
  assignments/12-savings/submissions/Gabriela-suares/SavingsAccountApp.java
  challenges/02-bank/submissions/gabriela-suares/src/Account.java
  challenges/02-bank/submissions/gabriela-suares/src/Customer.java
  challenges/02-bank/submissions/gabriela-suares/src/IDPBank.java
  readings/03-thinking/gabriela-suares.pdf
  readings/04-concepts/gabriela-suares(1).pdf
  readings/04-concepts/gabriela-suares.pdf
  readings/05-solid/gabriela-suares(2).pdf
  readings/05-solid/gabriela-suares.pdf
Labels: Review effort 3/5

#170 Assignments
  assignments/03-fibonacci/submissions/Pedro-Calil/src/Fibonacci.java
  assignments/04-elephant/submissions/Pedro-Calil/src/PassosElefante.java
  assignments/05-password/submissions/Pedro-Calil/src/FortalecerSenha.java
  assignments/06-heart/submissions/Pedro-Calil/src/HeartRates.java
  assignments/07-health/submissions/Pedro-Calil/src/HealthProfile.java
  assignments/08-palindrome/submissions/Pedro-Calil/src/PalindromeChecker.java
  assignments/09-collatz/submissions/Pedro-Calil/src/CollatzSequence.java
  assignments/10-median/submissions/Pedro-Calil/src/MedianCalculator.java
  assignments/11-parking/submissions/Pedro-Calil/src/ParkingGarage.java
Labels: Review effort 3/5

#169 Alterações IDP Bank
  challenges/02-bank/submissions/helenna-massarra/src/Account.java
  challenges/02-bank/submissions/helenna-massarra/src/CheckingAccount.java
  challenges/02-bank/submissions/helenna-massarra/src/Customer.java
  challenges/02-bank/submissions/helenna-massarra/src/IDPBank.java
  challenges/02-bank/submissions/helenna-massarra/src/SalaryAccount.java
  challenges/02-bank/submissions/helenna-massarra/src/SavingsAccount.java
  challenges/02-bank/submissions/helenna-massarra/src/Transaction.java
Labels: Review effort 3/5

#168 2025.1
  challenges/02-bank/submissions/pedro-pignata/src/Account.java
  challenges/02-bank/submissions/pedro-pignata/src/CheckingAccount.java
  challenges/02-bank/submissions/pedro-pignata/src/Customer.java
  challenges/02-bank/submissions/pedro-pignata/src/IDPBank.java
  challenges/02-bank/submissions/pedro-pignata/src/SalaryAccount.java
  challenges/02-bank/submissions/pedro-pignata/src/SavingsAccount.java
Labels: Review effort 3/5

#174 Realização da P1
  assignments/12-savings/submissions/samuel-abrao/src/SavingsAccount.java
  assignments/12-savings/submissions/samuel-abrao/src/SavingsAccountApp.java
  challenges/03-parking/submissions/Samuel-Abrao/src/Car.java
  challenges/03-parking/submissions/Samuel-Abrao/src/Motorcycle.java
  challenges/03-parking/submissions/Samuel-Abrao/src/ParkingApp.java
  challenges/03-parking/submissions/Samuel-Abrao/src/Truck.java
  challenges/03-parking/submissions/Samuel-Abrao/src/Vehicle.java
Labels: Review effort 2/5

#175 prova pratica AP1
  challenges/02-bank/submissions/yuri-santana/src/IDPBank.java
  challenges/02-bank/submissions/yuri-santana/src/models/Customer.java
  challenges/02-bank/submissions/yuri-santana/src/models/Transaction.java
  challenges/03-parking/submissions/yuri-santana/src/Car.java
  challenges/03-parking/submissions/yuri-santana/src/Motorcycle.java
  challenges/03-parking/submissions/yuri-santana/src/ParkingApp.java
  challenges/03-parking/submissions/yuri-santana/src/Truck.java
  challenges/03-parking/submissions/yuri-santana/src/Vehicle.java
Labels: Review effort 3/5

#177 prova e idpBank
  challenges/02-bank/submissions/artur-moraes/src/Account.java
  challenges/02-bank/submissions/artur-moraes/src/CheckingAccount.java
  challenges/02-bank/submissions/artur-moraes/src/Customer.java
  challenges/02-bank/submissions/artur-moraes/src/IDPBank.java
  challenges/02-bank/submissions/artur-moraes/src/SalaryAccount.java
  challenges/02-bank/submissions/artur-moraes/src/SavingsAccount.java
  challenges/02-bank/submissions/artur-moraes/src/Transaction.java
  challenges/03-parking/submissions/artur-moraes/src/Car.java
  challenges/03-parking/submissions/artur-moraes/src/Motorcycle.java
  challenges/03-parking/submissions/artur-moraes/src/ParkingApp.java
  challenges/03-parking/submissions/artur-moraes/src/Truck.java
  challenges/03-parking/submissions/artur-moraes/src/Vehicle.java
Labels: Review effort 3/5

#179 primeira prova gabriel
  challenges/03-parking/submissions/gabriel-delforge/src/Car.java
  challenges/03-parking/submissions/gabriel-delforge/src/Motorcycle.java
  challenges/03-parking/submissions/gabriel-delforge/src/ParkingApp.java
  challenges/03-parking/submissions/gabriel-delforge/src/Truck.java
  challenges/03-parking/submissions/gabriel-delforge/src/Vehicle.java
Labels: Review effort 2/5

#181 2025.1
  challenges/03-parking/submissions/rafael-lopes/src/Car.java
  challenges/03-parking/submissions/rafael-lopes/src/Motorcycle.java
  challenges/03-parking/submissions/rafael-lopes/src/ParkingApp.java
  challenges/03-parking/submissions/rafael-lopes/src/Truck.java
  challenges/03-parking/submissions/rafael-lopes/src/Vehicle.java
Labels: Review effort 2/5

#182 Prova prática Estacionamento - Allan Samuel
  challenges/03-parking/submissions/allan-samuel/src/Car.java
  challenges/03-parking/submissions/allan-samuel/src/Motorcycle.java
  challenges/03-parking/submissions/allan-samuel/src/ParkingApp.java
  challenges/03-parking/submissions/allan-samuel/src/Truck.java
  challenges/03-parking/submissions/allan-samuel/src/Vehicle.java
Labels: Review effort 2/5
